### ISSUE TITLE
Name and protocol resolution fail on monkey-patched socket.

### ISSUE THREAD

**Issue by entd** [veegee/guv#18]
Python requests library cannot resolve names like localhost on guv patched socket. 
``` python
import guv
guv.monkey_patch()
import requests
requests.get("http://127.0.0.1:8081/register")
requests.get("http://localhost:8081/register")
```
First request goes without problem, second fails with protocol error:
```
.../requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    413 
    414         except (ProtocolError, socket.error) as err:
--> 415             raise ConnectionError(err, request=request)
    416 
    417         except MaxRetryError as e:

ConnectionError: ('Connection aborted.', gaierror(-9, 'Address family for hostname not supported'))

```
I see it rather bizzare, something either with requests module or monkey patched socket is realy wrong. On non patched socket localhost request gets sent. Maybe patched socket resolves localhost wrong? Or rather this is bug in requests module?

**Comment by msoedov** [comment]
>>Or rather this is bug in requests module

@entd   did you have a chance to check it without <code>guv</code>? I mean 
``` 
import requests
requests.get("http://127.0.0.1:8081/register")
requests.get("http://localhost:8081/register")
```

**Comment by entd** [comment]
Yes I had: in bot cases i got 200.

**Comment by veegee** [comment]
This sounds like a DNS issue possibly. What happens when you do `export GUV_NO_GREENDNS=1` in the shell before you run your program?

**Comment by entd** [comment]
Definetely green DNS: exported flag fixed behaviour.

**Comment by veegee** [comment]
Ok, I'll fix this so it works with the green DNS

**Comment by veegee** [comment]
This seems to be an issue with dnspython3, which doesn't seem to respect `/etc/hosts`.

There are a few solutions to this:

- Deprecate dnspython3 support, and look into `gevent.dns` to see how they do it.
- Fix this issue directly in guv by reading `/etc/hosts`, `/etc/nsswitch.conf`, and so on in order to recognize those hostnames.
- Disable dnspython3 by default (currently enabled by default). DNS is pretty fast and it's cached, so guv will work just fine without dnspython3. In the use case that we're doing very frequent new name lookups (which most likely won't be local), then dnspython3 can be enabled with an environment variable or something.

**Comment by veegee** [comment]
It seems that libuv has come a long way since v1.0.0. I just saw that it now has this: http://docs.libuv.org/en/v1.x/dns.html

This is the solution. I'll implement this over the weekend.
